name: Build

on:
  push:
    branches: [ main ] # replace `main` with your default branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '20'
      - name: Build with Maven
        run: mvn clean install

